feat: handle query params
vadept/vachettp pull request #9
Opened 2020-12-14 12:59 UTC by sicardnicolas

2020-12-14 13:17 UTC, lx-dev-pm requested changes

2020-12-14 13:17 UTC, lx-dev-pm commented on request_parser.v
> +	for query_element in query_elements {
you should handle wrong param lists format:

example: `path/to/entity?param1=val1&param2=val2param3=val3`

2020-12-14 13:17 UTC, lx-dev-pm commented on request_parser.v
> +		query_params[query_parts[0]] = query_parts[1]
you should handle wrong format key/value format:

example: `path/to/entity?param1=val1=val11&param2=val2&crap&crap2`

2020-12-14 14:26 UTC, sicardnicolas commented on request_parser.v
> +	for query_element in query_elements {
i should've started by that actually

2020-12-14 14:28 UTC, sicardnicolas commented on request_parser.v
> +		query_params[query_parts[0]] = query_parts[1]
How do you think we should handle `crap` and `crap2`?
Should i accept then with a value set to `null`?
I don't event know if this is possible, might have to change the typing of the map to `map[string]?string` or something like that...

2020-12-14 17:41 UTC, sicardnicolas commented on request_parser.v
> +		query_params[query_parts[0]] = query_parts[1]
I've set default values to `''` as `null` doesn't exist in this language. 
Is it ok for you or do you prefer that i ignore those params completely?

2020-12-14 19:26 UTC, lx-dev-pm commented on request_parser.v
> +		query_params[query_parts[0]] = query_parts[1]
for me, we should manage this case.

At the end, there will be 3 actors (when the lib will be used):
 - the rest client : should not be able to submit parameters like that
 - the lib consumer : should not manage this point.
 - the lib (aka the server) : should not let incorrect html standard pass

there is no id `1` in your array, so an error should be raise.

the URI Query Parameters standards => https://tools.ietf.org/html/rfc3986#section-3.4

2020-12-15 11:02 UTC, lx-dev-pm approved these changes
:+1:

2020-12-15 11:04 UTC, merged